"""Update Plant model to allow NULL values or ensure valid data

Revision ID: 602ddfb40df6
Revises: 344844e068fb
Create Date: 2024-08-10 18:40:39.069051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602ddfb40df6'
down_revision = '344844e068fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
